#!/usr/bin/env python3
"""
Export verse-per-chapter counts from bible_source.json for books_meta.c (Phase 1.3).
Output: C array initializer for catholic_bible_verse_counts[73][150].
Run from project root or with --input path. Pipe to clipboard or append to books_meta.c.
"""

import json
import os
import sys

MAX_CHAPTERS = 150


def find_bible_source(root: str):
    for rel in ["assets/source/bible_source.json", "bible_source.json", "assets/bible_source.json"]:
        path = os.path.join(root, rel)
        if os.path.isfile(path):
            return path
    return os.path.join(root, "assets/source/bible_source.json")


def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    input_path = find_bible_source(root)
    if len(sys.argv) > 1 and sys.argv[1] == "--input":
        if len(sys.argv) < 3:
            print("Usage: export_verse_counts.py [--input PATH]", file=sys.stderr)
            sys.exit(1)
        input_path = sys.argv[2]
    if not os.path.isfile(input_path):
        print(f"Error: not found {input_path}", file=sys.stderr)
        sys.exit(1)

    with open(input_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    books = data.get("books", [])
    if len(books) != 73:
        print(f"Warning: expected 73 books, got {len(books)}", file=sys.stderr)

    lines = []
    lines.append("// Verse counts per chapter (0 = unused); generated by tools/export_verse_counts.py")
    lines.append("const uint16_t catholic_bible_verse_counts[CATHOLIC_BIBLE_BOOKS_COUNT][MAX_CHAPTERS_PER_BOOK] = {")

    for book_idx, book in enumerate(books):
        name = book.get("name", "?")
        chapters = book.get("chapters", {})
        # Sort by chapter number, get verse count per chapter
        ch_nums = sorted([int(k) for k in chapters.keys()])
        counts = []
        for ch in ch_nums:
            verses = chapters[str(ch)]
            counts.append(len(verses))
        # Pad to MAX_CHAPTERS_PER_BOOK with zeros (C doesn't need trailing zeros for static init, but we keep 150 for clarity)
        while len(counts) < MAX_CHAPTERS:
            counts.append(0)
        # Format one book per line (compact)
        count_str = ",".join(str(c) for c in counts)
        lines.append(f"    // {book_idx} {name}")
        lines.append(f"    {{{count_str}}},")

    lines.append("};")
    print("\n".join(lines))


if __name__ == "__main__":
    main()
